### ISSUE TITLE
Same blank timepicker-bs4 and datepicker-bs4 issue with multiple rows

### ISSUE THREAD

**Issue by MicJarek** [lesilent/timepicker-bs4#3]
Hi Lesilent,

First, thanks for fixing the minScreenWidth in both datepicker-bs4 and timepicker-bs4. Both work great now.

But I've noticed a strange behavior with the timepicker-bs4 when there are multiple rows present. For example: Repeatedly clicking on the time pickers on the same row (between start and end time) works fine. But when I click 1) the 'March Hare' start time picker (which displays OK), 2) then the 'Crush' end time picker (which displays OK), 3) and finally the 'March Hare' end time picker, the picker comes up blank (see attached images).

This ONLY happens when I cycle through the sequence the second time. The first time I click the sequence described above, all time pickers display correctly. And I can just repeat this same sequence over and over again, where the first sequence displays OK but repeating it again displays the blank. Also, if I click the icon for the blank picker, the picker will redisplay correctly. So really kind of puzzling.

Do you have any idea, off hand, why this might be happening?

NOTE: I just tried this with the datepicker-bs4 and the same thing happens with the datepicker-bs4 also.

![timepicker-bs4- (display correct)](https://github.com/lesilent/timepicker-bs4/assets/17038597/b3dee3f8-86c5-422c-8c6a-346ad3a346d5)
![timepicker-bs4- (display Issue)](https://github.com/lesilent/timepicker-bs4/assets/17038597/0b1233f1-7f0a-4d1b-a468-712edcb35f13)

**Comment by lesilent** [comment]
I can't replicate that issue. Can you create an example in jsfiddle or codepen?

**Comment by MicJarek** [comment]
Just a quick update, and sorry for the delay. I've been trying to finish up some more urgent app/db issues before going live so this one will have to wait a bit longer as it appears sporadic. BTW: I tried to reproduce the issue in jsfiddle per your suggestion but was not successful, so I'll get to it eventually, or maybe you can have a peak at it when the app is live (if that will help). Tks... :)

**Comment by lesilent** [comment]
Do you see any errors in the browser console? Offhand, the issue that you're seeing may occur if event to populate the contents of the popover doesn't get triggered. However, I can't reproduce the conditions to make that happen.

**Comment by MicJarek** [comment]
No... no errors in the console, but I did some debugging and figured out what the problem was: it was the 'duplicate' id's in the input fields. When I removed them, the timepicker (and datepicker) work fine now.

I am calling both the timepicker and datepicker using a class so I didn't think twice about the id's being an issue. Maybe it was because the id's were all identical (I know... I know... bad HTML) but those id's are copied from a hidden template and are ONLY used to identify the fields in the enclosing div to extract the values on save. I ended up using the 'name' property instead of the 'id' and that seems to have fixed the issue.

That page is quite complicated as it allows managers to insert n+1 records with the start/end date/time for each, and since I was calling the pickers using a class, I didn't think it mattered if there were id's or duplicate id's. Not sure if there is anything you need to do on your end, but I thought I'd share what I found just in case.

Anyway, all is good now and thanks for your help and the awesome pickers.

Cheers... 😊
