### ISSUE TITLE
Timepicker breaks if the value of the input is changed from somewhere else

### ISSUE THREAD

**Issue by bassauer-storms-media** [lesilent/timepicker-bs4#5]
I am using your plugin for a appointment form where possible dates / time-frames are fetched via ajax as soon as the user selects some values of dropdowns within the form. The data returned is used to render a tiny overview table above the form with a  button to pull the according timeframe over into the form.

![image](https://github.com/lesilent/timepicker-bs4/assets/25793506/81f20957-d251-499a-af23-8db2c51da255)

The timepicker works fine as long as nothing happens to the input externally. But as soon as I update the value of the timepicker's field (with a simple $().val(...)), the timepicker breaks like you can see within the screenshot

**Comment by lesilent** [comment]
I can't reproduce that on my end. Can you create an example in jsbin or jsfiddle?
