### ISSUE TITLE
Set default value

### ISSUE THREAD

**Issue by isayedahmad** [lesilent/timepicker-bs4#6]
I tried to pass viewTime: 09:00 in options but it has no effect.
$('#inputfield').timepicker({
                step: 300,
                format: 'h:mm A',
                viewTime: '09:00 AM',
            });
I need to pass a default value in case the input is empty, so I forced to update updatePicker in order to set my default value,
//comment old code
    // let viewTime = $input.data('viewtime');

    //new code to set time to 09:00 AM if the input value is empty
    let inputValue = $input.val();
    let viewTime =parseTime("09:00 AM");
    if (inputValue) {
        viewTime = parseTime(inputValue);
    }

I will suggest to add a default value option so user can set it.

**Comment by lesilent** [comment]
I'm not sure if having a default value as an option is really needed.  You can probably set a default value like this:

```
let $input = jQuery('#inputfield');
if (!$input.val()) {
    $input.val('09:00 AM');
}
```

Or by setting a value directly on the input tag itself:
```
<input type="text" id="inputfield" name="meet_time" value="09:00 AM" />
```

**Comment by isayedahmad** [comment]
sorry for late reply
this code has no effect :
let $input = jQuery('#inputfield');
if (!$input.val()) {
    $input.val('09:00 AM');
}
and the reason for not using this <input type="text" id="inputfield" name="meet_time" value="09:00 AM" /> because I want to keep the input box initially empty and set the default value to appear in the popup window
Thank you

**Comment by lesilent** [comment]
Makes sense. I've added a new `defaultTime` option to the newest version that should let you do that.
